# Generated by Django 2.2.1 on 2019-09-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_trainline_trainsearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationNo', models.CharField(max_length=6)),
                ('trainName', models.CharField(max_length=200)),
                ('stationID', models.CharField(max_length=6)),
                ('stationName', models.CharField(max_length=200)),
                ('stationDistince', models.CharField(max_length=200)),
                ('stationNameEng', models.CharField(max_length=200)),
            ],
        ),
    ]
